#name: Production
#
#on:
#  push:
#    branches:
#      - 'main'
#
#env:
#  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
#  NODE_VERSION: 16.13.0
#
#jobs:
#  setup:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ env.NODE_VERSION }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Cache node_modules
#        uses: actions/cache@v2
#        id: cache_id
#        with:
#          path: node_modules
#          key: node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
#      - name: Install dependencies
#        if: steps.cache_id.outputs.cache-hit != 'true'
#        run: yarn --frozen-lockfile
#
#
#  publish:
#    needs: setup
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up nodejs
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Restore cache
#        uses: actions/cache@v2
#        id: cache_id
#        with:
#          path: node_modules
#          key: node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
#      - name: Set GitHub account
#        run: |
#          # TODO: tetty から bot account にユーザーを変更する
#          git config --global user.name tetty
#          git config --global user.email dev.tetty@gmail.com
#      - name: Dry Release
#        run: yarn release:dry
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
#      - name: Release
#        run: yarn release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
